version: "3"
services:
  screeps:
    image: jomik/screeps-server:edge
    ports:
      - 21025:21025/tcp
    volumes:
      - ./config.yml:/screeps/config.yml
      - ./:/screeps/screepsmod-cli
    environment:
      STEAM_KEY: ${STEAM_KEY:?"Missing steam key"}
    restart: unless-stopped
  curl:
    image: quay.io/curl/curl:latest
    profiles:
      - debug
    network_mode: 'service:screeps'